# Manages the nightly.eclipse-pass.org deploy
# `docker-compose -f eclipse-pass.base.yml -f eclipse-pass.nightly.yml up`
version: '3.8'

services:
  auth:
    env_file:
      - .eclipse-pass.nightly_env

  pass-core:
    image: ghcr.io/eclipse-pass/pass-core-main:0.4.0-SNAPSHOT@sha256:a43c27f0e75cea2fe1eaa92f26e31564d0c73bd41f2d5ee1f242b202e27c1237
    env_file:
      - .eclipse-pass.nightly_env

  pass-ui:
    env_file:
      - .eclipse-pass.nightly_env

  postgres:
    env_file:
      - .eclipse-pass.nightly_env

  pass-ui-public:
    env_file:
      - .eclipse-pass.nightly_env

  idp:
    env_file:
      - .eclipse-pass.nightly_env

  loader:
    env_file:
      - .eclipse-pass.nightly_env
