# Manages the nightly.eclipse-pass.org deploy
# `docker-compose -f eclipse-pass.base.yml -f eclipse-pass.nightly.yml up`
version: '3.8'

services:
  auth:
    env_file:
      - .eclipse-pass.nightly_env

  pass-core:
    image: ghcr.io/eclipse-pass/pass-core-main:0.4.0-SNAPSHOT@sha256:434d15f26553dc4973c0786b54049b740073fe79df1f8d5d17f91b45c504c9ff
    env_file:
      - .eclipse-pass.nightly_env

  pass-ui:
    env_file:
      - .eclipse-pass.nightly_env

  postgres:
    env_file:
      - .eclipse-pass.nightly_env

  pass-ui-public:
    env_file:
      - .eclipse-pass.nightly_env

  idp:
    env_file:
      - .eclipse-pass.nightly_env

  loader:
    env_file:
      - .eclipse-pass.nightly_env
